apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-prometheus-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-prometheus-app
  template:
    metadata:
      labels:
        app: node-prometheus-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: node-app
        image: your-dockerhub-username/node-prometheus-k8s:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10